# Base configs
baseurl: "https://g-prossi.github.io/SophiaTheoktisto/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sophia T. Castro"
subtitle: "Discover the world with me!"
author: "Sophia T. Castro"
header:
 title: "Photography"
 subtitle: "by Sophia T. Castro"
footer:
 name: "Hey there, my name is Sophia"
 bio: "I'm an environmental scientist with a MSc in renewable energy and photographer."
 github: ""
web_design: "GPR"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/cstro.film?igsh=MWswcDJnbmV5eXBubA=="
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/sophtheok"
  github: "https://www.github.com/rampatra"
